import { DocPage, DocSection } from "@/components/DocPage";
import { CodeBlock } from "@/components/CodeBlock";

export default function CssVariablesFormatPage() {
  return (
    <DocPage
      title="CSS Variables"
      description="Export your generated theme as CSS custom properties scoped to a selector."
    >
      <DocSection title="Generate">
        <CodeBlock
          language="bash"
          code={`npx nightfall-css generate --format css-variables --output nightfall-theme.css`}
        />
      </DocSection>

      <DocSection title="Output Example">
        <CodeBlock
          language="css"
          filename="nightfall-theme.css"
          code={`/* Generated by Nightfall CSS v0.1.0 */
/* Direction: light → dark | Preset: neutral */

:root[data-theme="dark"],
.dark {
  /* Backgrounds */
  --color-bg-page: oklch(0.13 0.005 240);
  --color-bg-surface: oklch(0.17 0.005 240);
  --color-bg-elevated: oklch(0.21 0.005 240);
  --color-bg-overlay: oklch(0.25 0.005 240);

  /* Text */
  --color-text-heading: oklch(0.95 0.01 240);
  --color-text-body: oklch(0.82 0.01 240);
  --color-text-muted: oklch(0.60 0.01 240);

  /* Borders */
  --color-border-default: rgba(255, 255, 255, 0.08);
  --color-border-strong: rgba(255, 255, 255, 0.14);
  --color-border-subtle: rgba(255, 255, 255, 0.04);

  /* Brand */
  --color-brand-primary: oklch(0.62 0.20 260);
  --color-brand-text: oklch(0.98 0.005 260);

  /* Shadows */
  --shadow-sm: 0 1px 2px rgba(0, 0, 0, 0.30);
  --shadow-md: 0 4px 8px rgba(0, 0, 0, 0.40);
  --shadow-lg: 0 10px 20px rgba(0, 0, 0, 0.50);
}

/* System preference support */
@media (prefers-color-scheme: dark) {
  :root:not([data-theme="light"]) {
    --color-bg-page: oklch(0.13 0.005 240);
    --color-bg-surface: oklch(0.17 0.005 240);
    /* ... same values as above */
  }
}`}
        />
      </DocSection>

      <DocSection title="Using the Variables">
        <p>Import the generated file and use the variables in your styles:</p>
        <CodeBlock
          language="css"
          filename="styles.css"
          code={`@import './nightfall-theme.css';

.card {
  background: var(--color-bg-surface);
  border: 1px solid var(--color-border-default);
  color: var(--color-text-body);
  box-shadow: var(--shadow-md);
}

.card h2 {
  color: var(--color-text-heading);
}

.card .meta {
  color: var(--color-text-muted);
}

.btn-primary {
  background: var(--color-brand-primary);
  color: var(--color-brand-text);
}`}
        />
      </DocSection>

      <DocSection title="Custom Selector">
        <p>Change the scoping selector with <code>--selector</code>:</p>
        <CodeBlock
          language="bash"
          code={`# Scope to a class instead of data attribute
npx nightfall-css generate --format css-variables --selector ".dark-theme"

# Scope to :root for global application
npx nightfall-css generate --format css-variables --selector ":root"`}
        />
      </DocSection>

      <DocSection title="OKLCH vs Hex">
        <p>
          Nightfall outputs OKLCH values by default because they are more precise and
          enable CSS-native color manipulation. If you need hex fallbacks for older browsers,
          Nightfall includes both:
        </p>
        <CodeBlock
          language="css"
          code={`/* With fallbacks enabled */
--color-bg-page: #0f1012;
--color-bg-page: oklch(0.13 0.005 240);`}
        />
        <CodeBlock
          language="bash"
          code={`# Enable hex fallbacks
npx nightfall-css generate --format css-variables --fallback hex`}
        />
      </DocSection>

      <DocSection title="Browser Support">
        <p>
          OKLCH is supported in all modern browsers (Chrome 111+, Firefox 113+, Safari 15.4+).
          For older browsers, use the <code>--fallback hex</code> option to include hex values
          as progressive enhancement.
        </p>
      </DocSection>
    </DocPage>
  );
}
