import { DocPage, DocSection } from "@/components/DocPage";
import { CodeBlock } from "@/components/CodeBlock";

export default function BothDirectionsPage() {
  return (
    <DocPage
      title="Both Themes"
      description="Generate both light and dark themes in a single pass with --direction both."
    >
      <DocSection title="Overview">
        <p>
          The <code>--direction both</code> flag tells Nightfall to generate both the light
          and dark variants of your theme in one output file. This is useful when you want
          to ship a complete theme system from a single source of truth.
        </p>
        <CodeBlock
          language="bash"
          code={`npx nightfall-css scan --url http://localhost:3000 --direction both
npx nightfall-css generate --format css-variables --output themes.css`}
        />
      </DocSection>

      <DocSection title="Output Structure">
        <p>
          The generated file contains both themes scoped under appropriate selectors:
        </p>
        <CodeBlock
          language="css"
          filename="themes.css"
          code={`/* Auto-generated by Nightfall CSS */

:root, [data-theme="light"] {
  --bg-page: oklch(0.98 0.003 240);
  --bg-surface: oklch(1.00 0.000 0);
  --text-heading: oklch(0.15 0.01 240);
  --text-body: oklch(0.30 0.01 240);
  --border-default: rgba(0, 0, 0, 0.08);
  --shadow-md: 0 4px 6px rgba(0, 0, 0, 0.05);
  /* ... */
}

[data-theme="dark"] {
  --bg-page: oklch(0.13 0.005 240);
  --bg-surface: oklch(0.17 0.005 240);
  --text-heading: oklch(0.95 0.01 240);
  --text-body: oklch(0.82 0.01 240);
  --border-default: rgba(255, 255, 255, 0.08);
  --shadow-md: 0 4px 8px rgba(0, 0, 0, 0.40);
  /* ... */
}

@media (prefers-color-scheme: dark) {
  :root:not([data-theme="light"]) {
    --bg-page: oklch(0.13 0.005 240);
    --bg-surface: oklch(0.17 0.005 240);
    /* ... same as [data-theme="dark"] */
  }
}`}
        />
      </DocSection>

      <DocSection title="Roundtrip Stability">
        <p>
          Nightfall includes a roundtrip stability test: transforming light to dark and
          then back to light should produce colors within a delta-E of 2.0 from the originals.
          This proves that no information is lost during transformation.
        </p>
        <CodeBlock
          language="bash"
          code={`# Roundtrip test
npx nightfall-css scan --url http://localhost:3000 --direction both --verbose

# Output:
# [roundtrip] Testing light → dark → light stability
# [roundtrip] --bg-page:      ΔE = 0.8  ✓
# [roundtrip] --bg-surface:   ΔE = 1.1  ✓
# [roundtrip] --text-heading: ΔE = 0.4  ✓
# [roundtrip] --text-body:    ΔE = 0.6  ✓
# [roundtrip] --brand-primary: ΔE = 1.9 ✓
# [roundtrip] All 24 tokens within ΔE < 2.0 tolerance`}
        />
      </DocSection>

      <DocSection title="When to Use Both">
        <ul className="list-disc list-inside space-y-2 text-nf-text-muted">
          <li><strong className="text-nf-text">Design systems</strong> — Ship both themes as part of your token package.</li>
          <li><strong className="text-nf-text">Component libraries</strong> — Ensure every component works in both modes.</li>
          <li><strong className="text-nf-text">Validation</strong> — The roundtrip test catches any transformation that degrades quality.</li>
          <li><strong className="text-nf-text">System preference support</strong> — The generated <code>prefers-color-scheme</code> media query respects OS settings automatically.</li>
        </ul>
      </DocSection>

      <DocSection title="Combining with Presets">
        <p>
          You can combine <code>--direction both</code> with a preset to generate themed
          variants:
        </p>
        <CodeBlock
          language="bash"
          code={`# Generate both themes using the midnight preset
npx nightfall-css generate --direction both --preset midnight --output midnight-themes.css`}
        />
      </DocSection>
    </DocPage>
  );
}
