/**
 * Export as CSS custom properties.
 */

import type { TransformResult, TransformedToken } from '../core/transformer.js';

export interface CssVariablesOptions {
  selector?: string;
  prefix?: string;
  includeComments?: boolean;
}

/**
 * Generate CSS custom properties file from transform result.
 */
export function exportCssVariables(
  result: TransformResult,
  options: CssVariablesOptions = {}
): string {
  const {
    selector: customSelector,
    prefix = 'color',
    includeComments = true,
  } = options;

  const isDark = result.direction === 'light-to-dark';
  const selector = customSelector || (isDark
    ? ':root[data-theme="dark"],\n.dark'
    : ':root[data-theme="light"],\n.light');

  let css = '';

  if (includeComments) {
    css += `/* Generated by Nightfall CSS */\n`;
    css += `/* Direction: ${result.direction} */\n`;
    css += `/* Generated at: ${new Date().toISOString()} */\n\n`;
  }

  css += `${selector} {\n`;

  // Group tokens by category
  const groups = groupTokens(result.tokens);

  for (const [category, tokens] of Object.entries(groups)) {
    if (includeComments) {
      css += `  /* ${categoryLabel(category)} */\n`;
    }

    for (const token of tokens) {
      const varName = tokenToCssVar(token.role, prefix);
      css += `  ${varName}: ${token.transformed};\n`;
    }

    css += '\n';
  }

  // Add shadows if generated
  if (result.shadows && result.shadows.length > 0) {
    if (includeComments) {
      css += `  /* Shadows */\n`;
    }
    for (const shadow of result.shadows) {
      css += `  --${prefix}-${shadow.name}: ${shadow.value};\n`;
    }
    css += '\n';
  }

  css += '}\n';

  return css;
}

function tokenToCssVar(role: string, prefix: string): string {
  const parts = role.split('.');
  return `--${prefix}-${parts.join('-')}`;
}

function groupTokens(tokens: TransformedToken[]): Record<string, TransformedToken[]> {
  const groups: Record<string, TransformedToken[]> = {};

  for (const token of tokens) {
    const category = token.role.split('.')[0];
    if (!groups[category]) groups[category] = [];
    groups[category].push(token);
  }

  return groups;
}

function categoryLabel(category: string): string {
  const labels: Record<string, string> = {
    background: 'Backgrounds',
    text: 'Text',
    border: 'Borders',
    brand: 'Brand',
    accent: 'Accent',
    status: 'Status',
    shadow: 'Shadows',
    overlay: 'Overlays',
  };
  return labels[category] || category;
}
