/**
 * Export as W3C Design Tokens JSON format.
 */

import type { TransformResult } from '../core/transformer.js';

export function exportJsonTokens(result: TransformResult): string {
  const tokens: Record<string, any> = {
    $schema: 'https://design-tokens.github.io/community-group/format/',
    nightfall: {
      $description: `Generated by Nightfall CSS (${result.direction})`,
    },
  };

  for (const token of result.tokens) {
    const [group, name] = token.role.split('.');
    if (!tokens.nightfall[group]) {
      tokens.nightfall[group] = {};
    }

    tokens.nightfall[group][name] = {
      $type: 'color',
      $value: token.transformed,
      $description: `${token.role} — transformed from ${token.original}`,
      $extensions: {
        'com.nightfall': {
          originalValue: token.original,
          originalOklch: token.originalOklch,
          transformedOklch: token.transformedOklch,
          contrastRatio: token.contrastRatio,
          wasAutoFixed: token.wasAutoFixed || false,
        },
      },
    };
  }

  if (result.shadows) {
    tokens.nightfall.shadow = tokens.nightfall.shadow || {};
    for (const shadow of result.shadows) {
      tokens.nightfall.shadow[shadow.name.replace('shadow-', '')] = {
        $type: 'shadow',
        $value: shadow.value,
      };
    }
  }

  return JSON.stringify(tokens, null, 2);
}
