/**
 * Export as SCSS variables.
 */

import type { TransformResult } from '../core/transformer.js';

export function exportScssVariables(result: TransformResult): string {
  let scss = `// Generated by Nightfall CSS\n`;
  scss += `// Direction: ${result.direction}\n\n`;

  for (const token of result.tokens) {
    const varName = `$${token.role.replace('.', '-')}`;
    scss += `${varName}: ${token.transformed};\n`;
  }

  if (result.shadows) {
    scss += `\n// Shadows\n`;
    for (const shadow of result.shadows) {
      scss += `$${shadow.name}: ${shadow.value};\n`;
    }
  }

  // Also generate a map for easy iteration
  scss += `\n// Color map\n`;
  scss += `$nightfall-colors: (\n`;
  for (const token of result.tokens) {
    const key = token.role.replace('.', '-');
    scss += `  '${key}': ${token.transformed},\n`;
  }
  scss += `);\n`;

  return scss;
}
