/**
 * Export as Tailwind CSS config extension.
 */

import type { TransformResult, TransformedToken } from '../core/transformer.js';

/**
 * Generate a Tailwind config module from transform result.
 */
export function exportTailwindConfig(result: TransformResult): string {
  const isDark = result.direction === 'light-to-dark';
  const tokens = result.tokens;

  const find = (role: string) => tokens.find((t) => t.role === role)?.transformed || '';

  let config = `// Generated by Nightfall CSS\n`;
  config += `// Direction: ${result.direction}\n\n`;
  config += `/** @type {import('tailwindcss').Config} */\n`;
  config += `module.exports = {\n`;
  config += `  darkMode: 'class',\n`;
  config += `  theme: {\n`;
  config += `    extend: {\n`;
  config += `      colors: {\n`;

  // Backgrounds
  config += `        background: {\n`;
  config += `          DEFAULT: '${find('background.page')}',\n`;
  config += `          surface: '${find('background.surface')}',\n`;
  config += `          elevated: '${find('background.elevated')}',\n`;
  config += `        },\n`;

  // Text
  config += `        foreground: {\n`;
  config += `          DEFAULT: '${find('text.primary')}',\n`;
  config += `          muted: '${find('text.secondary')}',\n`;
  config += `          hint: '${find('text.tertiary')}',\n`;
  config += `        },\n`;

  // Border
  const borderDefault = find('border.default');
  const borderSubtle = find('border.subtle');
  if (borderDefault) {
    config += `        border: {\n`;
    config += `          DEFAULT: '${borderDefault}',\n`;
    if (borderSubtle) config += `          subtle: '${borderSubtle}',\n`;
    config += `        },\n`;
  }

  // Brand
  const brandPrimary = find('brand.primary');
  const brandSecondary = find('brand.secondary');
  if (brandPrimary) {
    config += `        brand: {\n`;
    config += `          DEFAULT: '${brandPrimary}',\n`;
    if (brandSecondary) config += `          secondary: '${brandSecondary}',\n`;
    config += `        },\n`;
  }

  // Accent
  const accentLink = find('accent.link');
  if (accentLink) {
    config += `        accent: {\n`;
    config += `          DEFAULT: '${accentLink}',\n`;
    config += `        },\n`;
  }

  // Status colors
  const statusColors = ['success', 'warning', 'error', 'info'];
  for (const status of statusColors) {
    const color = find(`status.${status}`);
    if (color) {
      config += `        ${status}: '${color}',\n`;
    }
  }

  config += `      },\n`; // close colors

  // Shadows
  if (result.shadows && result.shadows.length > 0) {
    config += `      boxShadow: {\n`;
    for (const shadow of result.shadows) {
      const name = shadow.name.replace('shadow-', '');
      config += `        '${name}': '${shadow.value}',\n`;
    }
    config += `      },\n`;
  }

  config += `    },\n`; // close extend
  config += `  },\n`; // close theme
  config += `};\n`;

  return config;
}
