import { DocPage, DocSection } from "@/components/DocPage";
import { CodeBlock } from "@/components/CodeBlock";

export default function HowItWorksPage() {
  return (
    <DocPage
      title="How it works"
      description="Under the hood: color graphs, OKLCH transformations, and bidirectional theme generation."
    >
      <DocSection title="The Pipeline">
        <p>Nightfall follows a three-step pipeline: <strong>Scan → Analyze → Generate</strong>.</p>
        <ol className="list-decimal list-inside space-y-3 text-nf-text-muted">
          <li><strong className="text-nf-text">Launch Playwright</strong> — visits each route in a headless browser</li>
          <li><strong className="text-nf-text">Auto-Detect Direction</strong> — determines light or dark mode by analyzing background lightness in OKLCH</li>
          <li><strong className="text-nf-text">DOM Walk</strong> — traverses every visible element, collecting background-color, color, border-color, box-shadow, and more</li>
          <li><strong className="text-nf-text">Build Color Graph</strong> — creates a relationship map of what sits on what</li>
          <li><strong className="text-nf-text">Classify Roles</strong> — assigns semantic roles (background.page, text.primary, brand.primary, etc.)</li>
          <li><strong className="text-nf-text">Transform</strong> — applies OKLCH-space transformations based on direction</li>
          <li><strong className="text-nf-text">Export</strong> — writes the theme in your chosen format</li>
        </ol>
      </DocSection>

      <DocSection title="Color Graph">
        <p>The color graph maps relationships between colors in your UI:</p>
        <CodeBlock
          language="bash"
          code={`Page Background (#ffffff)
  └── Card Surface (#f8f9fa)
        ├── Card Border (#e5e7eb)
        ├── Heading Text (#111827)    → 18.1:1 contrast
        ├── Body Text (#374151)       → 11.2:1 contrast
        ├── Muted Text (#9ca3af)      →  4.6:1 contrast
        └── Accent Button (#2563eb)   →  4.8:1 contrast
              └── Button Text (#ffffff)`}
        />
        <p>Each node knows its parent (what it sits on) and the contrast ratio between them. This graph is preserved during transformation.</p>
      </DocSection>

      <DocSection title="OKLCH Color Space">
        <p>
          All transformations happen in OKLCH — a perceptually uniform color space where equal numerical changes
          produce equal visual changes. This means a dark theme generated by Nightfall looks natural, not mathematically inverted.
        </p>
        <ul className="list-disc list-inside space-y-2 text-nf-text-muted">
          <li><strong className="text-nf-text">L</strong> — Lightness (0 = black, 1 = white)</li>
          <li><strong className="text-nf-text">C</strong> — Chroma (saturation intensity)</li>
          <li><strong className="text-nf-text">H</strong> — Hue (0-360 degrees)</li>
        </ul>
      </DocSection>

      <DocSection title="Direction Detection">
        <p>Nightfall auto-detects your theme direction by:</p>
        <ol className="list-decimal list-inside space-y-2 text-nf-text-muted">
          <li>Sampling the page background color</li>
          <li>Computing weighted average lightness of all background surfaces</li>
          <li>If average L {'>'} 0.6 → light mode → generates dark</li>
          <li>If average L {'<'} 0.4 → dark mode → generates light</li>
          <li>If ambiguous (0.4–0.6) → falls back to --direction flag</li>
        </ol>
      </DocSection>
    </DocPage>
  );
}
